"""alter product table

Revision ID: 558cc575f6fe
Revises: 323e3039d4a8
Create Date: 2026-03-31 14:56:01.538339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558cc575f6fe'
down_revision: Union[str, Sequence[str], None] = '323e3039d4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_price')
    # ### end Alembic commands ###
